name: Get latest release version
on:
  schedule:
    - cron:  '0 13 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually run build'
        required: false
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: sync
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/lightningnetwork/lnd/releases/latest | \
          jq -r ".tag_name" > release-versions/lnd-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Emad-salah'
          git config --global user.email 'emads14@gmail.com'
          git commit -am "New release version"
          git push
